/** Copyright 1984-2016 The MathWorks, Inc. */
//>>built
require({cache:{"dojo/require":function(){define(["./_base/loader"],function(c){return{dynamic:0,normalize:function(d){return d},load:c.require}})},"dojo/selector/lite":function(){define(["../has","../_base/kernel"],function(c,d){var g=document.createElement("div"),b=g.matches||g.webkitMatchesSelector||g.mozMatchesSelector||g.msMatchesSelector||g.oMatchesSelector,f=g.querySelectorAll,l=/([^\s,](?:"(?:\\.|[^"])+"|'(?:\\.|[^'])+'|[^,])*)/g;c.add("dom-matches-selector",!!b);c.add("dom-qsa",!!f);var a=
function(l,n){if(k&&-1<l.indexOf(","))return k(l,n);var p=n?n.ownerDocument||n:d.doc||document,b=(f?/^([\w]*)#([\w\-]+$)|^(\.)([\w\-\*]+$)|^(\w+$)/:/^([\w]*)#([\w\-]+)(?:\s+(.*))?$|(?:^|(>|.+\s+))([\w\-\*]+)(\S*$)/).exec(l);n=n||p;if(b){if(b[2]){var c=d.byId?d.byId(b[2],p):p.getElementById(b[2]);if(!c||b[1]&&b[1]!=c.tagName.toLowerCase())return[];if(n!=p)for(p=c;p!=n;)if(p=p.parentNode,!p)return[];return b[3]?a(b[3],c):[c]}if(b[3]&&n.getElementsByClassName)return n.getElementsByClassName(b[4]);if(b[5])if(c=
n.getElementsByTagName(b[5]),b[4]||b[6])l=(b[4]||"")+b[6];else return c}if(f)return 1===n.nodeType&&"object"!==n.nodeName.toLowerCase()?h(n,l,n.querySelectorAll):n.querySelectorAll(l);c||(c=n.getElementsByTagName("*"));for(var b=[],p=0,g=c.length;p<g;p++){var z=c[p];1==z.nodeType&&e(z,l,n)&&b.push(z)}return b},h=function(a,b,e){var d=a,c=a.getAttribute("id"),f=c||"__dojo__",k=a.parentNode,g=/^\s*[+~]/.test(b);if(g&&!k)return[];c?f=f.replace(/'/g,"\\$\x26"):a.setAttribute("id",f);g&&k&&(a=a.parentNode);
b=b.match(l);for(k=0;k<b.length;k++)b[k]="[id\x3d'"+f+"'] "+b[k];b=b.join(",");try{return e.call(a,b)}finally{c||d.removeAttribute("id")}};if(!c("dom-matches-selector"))var e=function(){function a(b,e,c){var l=e.charAt(0);if('"'==l||"'"==l)e=e.slice(1,-1);e=e.replace(/\\/g,"");var d=f[c||""];return function(a){return(a=a.getAttribute(b))&&d(a,e)}}function b(a){return function(b,e){for(;(b=b.parentNode)!=e;)if(a(b,e))return!0}}function e(a){return function(b,e){b=b.parentNode;return a?b!=e&&a(b,e):
b==e}}function c(a,b){return a?function(e,c){return b(e)&&a(e,c)}:b}var l="div"==g.tagName?"toLowerCase":"toUpperCase",d={"":function(a){a=a[l]();return function(b){return b.tagName==a}},".":function(a){var b=" "+a+" ";return function(e){return-1<e.className.indexOf(a)&&-1<(" "+e.className+" ").indexOf(b)}},"#":function(a){return function(b){return b.id==a}}},f={"^\x3d":function(a,b){return 0==a.indexOf(b)},"*\x3d":function(a,b){return-1<a.indexOf(b)},"$\x3d":function(a,b){return a.substring(a.length-
b.length,a.length)==b},"~\x3d":function(a,b){return-1<(" "+a+" ").indexOf(" "+b+" ")},"|\x3d":function(a,b){return 0==(a+"-").indexOf(b+"-")},"\x3d":function(a,b){return a==b},"":function(a,b){return!0}},k={};return function(l,f,g){var h=k[f];if(!h){if(f.replace(/(?:\s*([> ])\s*)|(#|\.)?((?:\\.|[\w-])+)|\[\s*([\w-]+)\s*(.?=)?\s*("(?:\\.|[^"])+"|'(?:\\.|[^'])+'|(?:\\.|[^\]])*)\s*\]/g,function(l,f,k,g,q,F,G){g?h=c(h,d[k||""](g.replace(/\\/g,""))):f?h=(" "==f?b:e)(h):q&&(h=c(h,a(q,G,F)));return""}))throw Error("Syntax error in query");
if(!h)return!0;k[f]=h}return h(l,g)}}();if(!c("dom-qsa"))var k=function(b,e){for(var c=b.match(l),f=[],d=0;d<c.length;d++){b=new String(c[d].replace(/\s*$/,""));b.indexOf=escape;for(var k=a(b,e),g=0,h=k.length;g<h;g++){var t=k[g];f[t.sourceIndex]=t}}c=[];for(d in f)c.push(f[d]);return c};a.match=b?function(a,e,c){return c&&9!=c.nodeType?h(c,e,function(e){return b.call(a,e)}):b.call(a,e)}:e;return a})},"xstyle/core/load-css":function(){define([],function(){function c(c){if(b.createStyleSheet){var a=
b.createStyleSheet();a.cssText=c;return a.owningElement}a=b.createElement("style");a.setAttribute("type","text/css");a.appendChild(b.createTextNode(c));f.insertBefore(a,f.firstChild);return a}function d(d,a,h){var e=g[d];if(e)return k=c(e),a(k);var k=b.createElement("link");k.type="text/css";k.rel="stylesheet";k.href=d;var y=!h||!1!==h.wait;h=(h=navigator.userAgent.match(/AppleWebKit\/(\d+\.?\d*)/))&&+h[1];if(null===k.onload&&!(536>h))k.onload=function(){k.onload=null;k.onerror=null;y&&a(k)},k.onerror=
function(){console.error("Error loading stylesheet "+d);y&&a(k)};else if(y)var n=setInterval(function(){k.style&&(clearInterval(n),a(k))},15);(f||b.getElementsByTagName("head")[0]).appendChild(k);y||a(k)}var g="undefined"==typeof _css_cache?{}:_css_cache,b=document,f=b.head;d.insertCss=c;return d})},"dijit/main":function(){define(["dojo/_base/kernel"],function(c){return c.dijit})},"dojox/main":function(){define(["dojo/_base/kernel"],function(c){return c.dojox})},"MW/utils/BrowserCheck":function(){define("dojo/_base/window dojo/window dojo/dom-construct dojo/has dojo/i18n!l10n/nls/unsupportedErrorPage ./detect/css ./detect/object".split(" "),
function(c,d,g,b,f){var l={isBrowserValid:function(){var a=!0;b("quirks")?a=!1:b("css-enabled")?b("css-border-radius")?b("css-text-overflow")?b("object-create")||(a=!1):a=!1:a=!1:a=!1;return a},displayErrorAsOverlay:function(){g.create("div",{style:{position:"absolute",left:"0%",top:"0%","background-color":"grey","-moz-opacity":"0.7",opacity:".70",filter:"alpha(opacity\x3d70)",width:"100%",height:"100%",zIndex:"90"},id:"fadeDiv"},c.body());g.create("div",{style:{position:"relative",margin:"auto",
"margin-top":"12.35%",width:"400px",height:"300px",padding:"10px",border:"2px solid black","background-color":"#ffffff","z-index":"100","font-family":"Sans-serif"},id:"unsupportedBrowser","class":"content_module"},c.body()).innerHTML=f.unsupportedError}};return{load:function(a,b,e){l.isBrowserValid()?e():a?c.global.location=a:l.displayErrorAsOverlay()}}})},"dojo/window":function(){define("./_base/lang ./sniff ./_base/window ./dom ./dom-geometry ./dom-style ./dom-construct".split(" "),function(c,d,
g,b,f,l,a){d.add("rtl-adjust-position-for-verticalScrollBar",function(b,c){var d=g.body(c),l=a.create("div",{style:{overflow:"scroll",overflowX:"visible",direction:"rtl",visibility:"hidden",position:"absolute",left:"0",top:"0",width:"64px",height:"64px"}},d,"last"),p=a.create("div",{style:{overflow:"hidden",direction:"ltr"}},l,"last"),h=0!=f.position(p).x;l.removeChild(p);d.removeChild(l);return h});d.add("position-fixed-support",function(b,c){var d=g.body(c),l=a.create("span",{style:{visibility:"hidden",
position:"fixed",left:"1px",top:"1px"}},d,"last"),p=a.create("span",{style:{position:"fixed",left:"0",top:"0"}},l,"last"),h=f.position(p).x!=f.position(l).x;l.removeChild(p);d.removeChild(l);return h});var h={getBox:function(a){a=a||g.doc;var b="BackCompat"==a.compatMode?g.body(a):a.documentElement,c=f.docScroll(a);if(d("touch")){var l=h.get(a);a=l.innerWidth||b.clientWidth;b=l.innerHeight||b.clientHeight}else a=b.clientWidth,b=b.clientHeight;return{l:c.x,t:c.y,w:a,h:b}},get:function(a){if(d("ie")&&
h!==document.parentWindow){a.parentWindow.execScript("document._parentWindow \x3d window;","Javascript");var b=a._parentWindow;a._parentWindow=null;return b}return a.parentWindow||a.defaultView},scrollIntoView:function(a,c){try{a=b.byId(a);var h=a.ownerDocument||g.doc,n=g.body(h),p=h.documentElement||n.parentNode,s=d("ie"),B=d("webkit");if(!(a==n||a==p))if(!d("mozilla")&&(!s&&!B&&!d("opera")&&!d("trident"))&&"scrollIntoView"in a)a.scrollIntoView(!1);else{var H="BackCompat"==h.compatMode,z=Math.min(n.clientWidth||
p.clientWidth,p.clientWidth||n.clientWidth),C=Math.min(n.clientHeight||p.clientHeight,p.clientHeight||n.clientHeight),h=B||H?n:p,t=c||f.position(a),q=a.parentNode,B=function(a){return 6>=s||7==s&&H?!1:d("position-fixed-support")&&"fixed"==l.get(a,"position").toLowerCase()},A=this,E=function(a,b,c){"BODY"==a.tagName||"HTML"==a.tagName?A.get(a.ownerDocument).scrollBy(b,c):(b&&(a.scrollLeft+=b),c&&(a.scrollTop+=c))};if(!B(a))for(;q;){q==n&&(q=h);var m=f.position(q),u=B(q),r="rtl"==l.getComputedStyle(q).direction.toLowerCase();
if(q==h){m.w=z;m.h=C;if(h==p&&(s||d("trident"))&&r)m.x+=h.offsetWidth-m.w;if(0>m.x||!s||9<=s||d("trident"))m.x=0;if(0>m.y||!s||9<=s||d("trident"))m.y=0}else{var v=f.getPadBorderExtents(q);m.w-=v.w;m.h-=v.h;m.x+=v.l;m.y+=v.t;var w=q.clientWidth,F=m.w-w;0<w&&0<F&&(r&&d("rtl-adjust-position-for-verticalScrollBar")&&(m.x+=F),m.w=w);w=q.clientHeight;F=m.h-w;0<w&&0<F&&(m.h=w)}u&&(0>m.y&&(m.h+=m.y,m.y=0),0>m.x&&(m.w+=m.x,m.x=0),m.y+m.h>C&&(m.h=C-m.y),m.x+m.w>z&&(m.w=z-m.x));var G=t.x-m.x,D=t.y-m.y,J=G+t.w-
m.w,K=D+t.h-m.h,x,I;if(0<J*G&&(q.scrollLeft||q==h||q.scrollWidth>q.offsetHeight)){x=Math[0>G?"max":"min"](G,J);if(r&&(8==s&&!H||9<=s||d("trident")))x=-x;I=q.scrollLeft;E(q,x,0);x=q.scrollLeft-I;t.x-=x}if(0<K*D&&(q.scrollTop||q==h||q.scrollHeight>q.offsetHeight))x=Math.ceil(Math[0>D?"max":"min"](D,K)),I=q.scrollTop,E(q,0,x),x=q.scrollTop-I,t.y-=x;q=q!=h&&!u&&q.parentNode}}}catch(N){console.error("scrollIntoView: "+N),a.scrollIntoView(!1)}}};c.setObject("dojo.window",h);return h})},"dojo/i18n":function(){define("./_base/kernel require ./has ./_base/array ./_base/config ./_base/lang ./_base/xhr ./json module".split(" "),
function(c,d,g,b,f,l,a,h,e){g.add("dojo-preload-i18n-Api",1);var k=c.i18n={},y=/(^.*(^|\/)nls)(\/|$)([^\/]*)\/?([^\/]*)/,n=function(a,b,c,d){var l=[c+d];b=b.split("-");for(var f="",e=0;e<b.length;e++)if(f+=(f?"-":"")+b[e],!a||a[f])l.push(c+f+"/"+d),l.specificity=f;return l},p={},s=function(a,b,d){d=d?d.toLowerCase():c.locale;a=a.replace(/\./g,"/");b=b.replace(/\./g,"/");return/root/i.test(d)?a+"/nls/"+b:a+"/nls/"+d+"/"+b},B=c.getL10nName=function(a,b,c){return e.id+"!"+s(a,b,c)},H=function(a,b,c,
d,f,e){a([b],function(g){var h=l.clone(g.root||g.ROOT),k=n(!g._v1x&&g,f,c,d);a(k,function(){for(var a=1;a<k.length;a++)h=l.mixin(l.clone(h),arguments[a]);p[b+"/"+f]=h;h.$locale=k.specificity;e()})})},z=function(a){var b=f.extraLocale||[],b=l.isArray(b)?b:[b];b.push(a);return b},C=function(a,d,f){if(g("dojo-preload-i18n-Api")){var e=a.split("*"),k="preload"==e[1];k&&(p[a]||(p[a]=1,m(e[2],h.parse(e[3]),1,d)),f(1));if(!(e=k))A&&E.push([a,d,f]),e=A;if(e)return}a=y.exec(a);var q=a[1]+"/",n=a[5]||a[4],
r=q+n,e=(a=a[5]&&a[4])||c.locale||"",L=r+"/"+e;a=a?[e]:z(e);var M=a.length,s=function(){--M||f(l.delegate(p[L]))};b.forEach(a,function(a){var b=r+"/"+a;g("dojo-preload-i18n-Api")&&u(b);p[b]?s():H(d,r,q,n,a,s)})};if(g("dojo-unit-tests"))var t=k.unitTests=[];g("dojo-preload-i18n-Api");var q=k.normalizeLocale=function(a){a=a?a.toLowerCase():c.locale;return"root"==a?"ROOT":a},A=0,E=[],m=k._preloadLocalizations=function(a,f,e,g){function h(a,b){g.isXdUrl(d.toUrl(a+".js"))||e?g([a],b):w([a],b,g)}function k(a,
b){for(var c=a.split("-");c.length;){if(b(c.join("-")))return;c.pop()}b("ROOT")}function m(){for(--A;!A&&E.length;)C.apply(null,E.shift())}function n(c){c=q(c);k(c,function(e){if(0<=b.indexOf(f,e)){var n=a.replace(/\./g,"/")+"_"+e;A++;h(n,function(a){for(var b in a){var f=a[b],h=b.match(/(.+)\/([^\/]+)$/),n;if(h){n=h[2];h=h[1]+"/";f._localized=f._localized||{};var q;if("ROOT"===e){var D=q=f._localized;delete f._localized;D.root=f;p[d.toAbsMid(b)]=D}else q=f._localized,p[d.toAbsMid(h+n+"/"+e)]=f;e!==
c&&function(a,b,f,e){var h=[],n=[];k(c,function(c){e[c]&&(h.push(d.toAbsMid(a+c+"/"+b)),n.push(d.toAbsMid(a+b+"/"+c)))});h.length?(A++,g(h,function(){for(var e=0;e<h.length;e++)f=l.mixin(l.clone(f),arguments[e]),p[n[e]]=f;p[d.toAbsMid(a+b+"/"+c)]=l.clone(f);m()})):p[d.toAbsMid(a+b+"/"+c)]=f}(h,n,f,q)}}m()});return!0}return!1})}g=g||d;n();b.forEach(c.config.extraLocale,n)},u=function(){},r={},v=new Function("__bundle","__checkForLegacyModules","__mid","__amdValue","var define \x3d function(mid, factory){define.called \x3d 1; __amdValue.result \x3d factory || mid;},\t   require \x3d function(){define.called \x3d 1;};try{define.called \x3d 0;eval(__bundle);if(define.called\x3d\x3d1)return __amdValue;if((__checkForLegacyModules \x3d __checkForLegacyModules(__mid)))return __checkForLegacyModules;}catch(e){}try{return eval('('+__bundle+')');}catch(e){return e;}"),
w=function(c,f,e){var d=[];b.forEach(c,function(b){function c(a){a=v(a,u,b,r);a===r?d.push(p[f]=r.result):(a instanceof Error&&(console.error("failed to evaluate i18n bundle; url\x3d"+f,a),a={}),d.push(p[f]=/nls\/[^\/]+\/[^\/]+$/.test(f)?a:{root:a,_v1x:1}))}var f=e.toUrl(b+".js");if(p[f])d.push(p[f]);else{var l=e.syncLoadNls(b);if(l)d.push(l);else if(a)a.get({url:f,sync:!0,load:c,error:function(){d.push(p[f]={})}});else try{e.getText(f,!0,c)}catch(h){d.push(p[f]={})}}});f&&f.apply(null,d)},u=function(a){for(var b,
f=a.split("/"),d=c.global[f[0]],e=1;d&&e<f.length-1;d=d[f[e++]]);d&&((b=d[f[e]])||(b=d[f[e].replace(/-/g,"_")]),b&&(p[a]=b));return b};k.getLocalization=function(a,b,c){var f;a=s(a,b,c);C(a,!d.isXdUrl(d.toUrl(a+".js"))?function(a,b){w(a,b,d)}:d,function(a){f=a});return f};g("dojo-unit-tests")&&t.push(function(a){a.register("tests.i18n.unit",function(a){var b;b=v("{prop:1}",u,"nonsense",r);a.is({prop:1},b);a.is(void 0,b[1]);b=v("({prop:1})",u,"nonsense",r);a.is({prop:1},b);a.is(void 0,b[1]);b=v("{'prop-x':1}",
u,"nonsense",r);a.is({"prop-x":1},b);a.is(void 0,b[1]);b=v("({'prop-x':1})",u,"nonsense",r);a.is({"prop-x":1},b);a.is(void 0,b[1]);b=v("define({'prop-x':1})",u,"nonsense",r);a.is(r,b);a.is({"prop-x":1},r.result);b=v("define('some/module', {'prop-x':1})",u,"nonsense",r);a.is(r,b);a.is({"prop-x":1},r.result);b=v("this is total nonsense and should throw an error",u,"nonsense",r);a.is(b instanceof Error,!0)})});return l.mixin(k,{dynamic:!0,normalize:function(a,b){return/^\./.test(a)?b(a):a},load:C,cache:p,
getL10nName:B})})},"MW/utils/detect/css":function(){define(["dojo/has"],function(c){function d(b,c){var a=!1,d=b.charAt(0).toUpperCase()+b.slice(1),e=g.length,k=c.style;if("string"===typeof k[b])a=!0;else for(;e;)if(e-=1,"string"===typeof k[g[e]+d]){a=!0;break}return a}var g=["Webkit","Moz","O","ms","Khtml"],b=c.add;b("css-enabled",function(b,c,a){var d;b=c.documentElement;var e;if(!(e=c.body))d=!0,e=b.insertBefore(c.createElement("body"),b.firstChild);b=e;e=a.style.display;a.style.display="none";
b.insertBefore(a,b.firstChild);c=0===a.offsetWidth;b.removeChild(a);a.style.display=e;d&&b.parentNode.removeChild(b);return c});b("css-content-box",function(b,d,a){var h,e;b=d.documentElement;var g=null;if(c("css-enabled")){if(!(e=d.body))h=!0,e=b.insertBefore(d.createElement("body"),b.firstChild);a.style.cssText="position: absolute; top: -4000px; width: 40px; height: 40px; border: 1px solid black;";e.insertBefore(a,e.firstChild);g=40===a.clientWidth;e.removeChild(a);a.style.cssText=""}h&&e.parentNode.removeChild(e);
return g});b("css-position-fixed",function(b,d,a){var g,e,k=d.documentElement,y=null;if(c("css-enabled")){b=a.cloneNode(!1);if(!(e=d.body))g=!0,e=k.insertBefore(d.createElement("body"),k.firstChild);d=e.style.cssText;e.style.cssText="padding:0;margin:0";a.style.cssText="position:fixed;top:42px";e.insertBefore(b,e.firstChild);e.insertBefore(a,b);y=a.offsetTop!==b.offsetTop;e.removeChild(a);e.removeChild(b);e.style.cssText=d;a.style.cssText=""}g&&e.parentNode.removeChild(e);return y});b("css-rgba",
function(b,d,a){b=/^rgba/;d=null;if(c("css-enabled"))try{a.style.color="rgba(1,1,1,0.5)",d=b.test(a.style.color),a.style.color=""}catch(g){}return d});b("css-border-radius",function(b,c,a){return d("borderRadius",a)});b("css-box-shadow",function(b,c,a){return d("boxShadow",a)});b("css-box-sizing",function(b,c,a){return d("boxSizing",a)});b("css-opacity",function(b,c,a){return d("opacity",a)});b("css-opacity-filter",function(b,d){return!c("css-opacity")&&"undefined"!==typeof d.documentElement.filters});
b("css-resize",function(b,c,a){return d("resize",a)});b("css-selectable",function(b,c,a){return d("userSelect",a)});b("css-style-float",function(b,c,a){return d("styleFloat",a)});b("css-pointerevents",function(b,c,a){return d("pointerEvents",a)});b("css-text-overflow",function(b,c,a){return d("textOverflow",a)});b("css-text-shadow",function(b,c,a){return d("textShadow",a)});b("css-transform",function(b,c,a){return d("transform",a)});return c})},"MW/utils/detect/object":function(){define(["dojo/has"],
function(c){var d=c.add,g={}.toString,b=Object;d("object-create",function(){return"[object Function]"===g.call(b.create)});d("object-getprototypeof",function(){return"[object Function]"===g.call(b.getPrototypeOf)});d("object-seal",function(){return"[object Function]"===g.call(b.seal)});d("object-freeze",function(){return"[object Function]"===g.call(b.freeze)});d("object-issealed",function(){return"[object Function]"===g.call(b.isSealed)});d("object-isfrozen",function(){return"[object Function]"===
g.call(b.isFrozen)});d("object-keys",function(){return"[object Function]"===g.call(b.keys)});d("object-preventextensions",function(){return"[object Function]"===g.call(b.preventExtensions)});d("object-isextensible",function(){return"[object Function]"===g.call(b.isExtensible)});d("object-defineproperty",function(){return"[object Function]"===g.call(b.defineProperty)});d("object-defineproperties",function(){return"[object Function]"===g.call(b.defineProperties)});d("object-getownpropertydescriptor",
function(){return"[object Function]"===g.call(b.getOwnPropertyDescriptor)});d("object-getownpropertynames",function(){return"[object Function]"===g.call(b.getOwnPropertyNames)});d("object-es5",function(){return c("object-create")&&c("object-defineproperties")&&c("object-defineproperty")&&c("object-freeze")&&c("object-getownpropertydescriptor")&&c("object-getownpropertynames")&&c("object-getprototypeof")&&c("object-isextensible")&&c("object-isfrozen")&&c("object-issealed")&&c("object-keys")&&c("object-preventextensions")&&
c("object-seal")});return c})},"*now":function(c){c(['dojo/i18n!*preload*uisetcolor/nls/browsercheck*["ar","ca","cs","da","de","el","en-gb","en-us","es-es","fi-fi","fr-fr","he-il","hu","it-it","ja-jp","ko-kr","nl-nl","nb","pl","pt-br","pt-pt","ru","sk","sl","sv","th","tr","zh-tw","zh-cn","ROOT"]'])}}});define("uisetcolor/browsercheck",[],1);
//# sourceMappingURL=browsercheck.js.map