/** Copyright 1984-2016 The MathWorks, Inc. */
//>>built
require({cache:{"dojo/require":function(){define(["./_base/loader"],function(b){return{dynamic:0,normalize:function(d){return d},load:b.require}})},"dojo/selector/lite":function(){define(["../has","../_base/kernel"],function(b,d){var f=document.createElement("div"),c=f.matches||f.webkitMatchesSelector||f.mozMatchesSelector||f.msMatchesSelector||f.oMatchesSelector,g=f.querySelectorAll,l=/([^\s,](?:"(?:\\.|[^"])+"|'(?:\\.|[^'])+'|[^,])*)/g;b.add("dom-matches-selector",!!c);b.add("dom-qsa",!!g);var a=
function(l,p){if(m&&-1<l.indexOf(","))return m(l,p);var c=p?p.ownerDocument||p:d.doc||document,b=(g?/^([\w]*)#([\w\-]+$)|^(\.)([\w\-\*]+$)|^(\w+$)/:/^([\w]*)#([\w\-]+)(?:\s+(.*))?$|(?:^|(>|.+\s+))([\w\-\*]+)(\S*$)/).exec(l);p=p||c;if(b){if(b[2]){var q=d.byId?d.byId(b[2],c):c.getElementById(b[2]);if(!q||b[1]&&b[1]!=q.tagName.toLowerCase())return[];if(p!=c)for(c=q;c!=p;)if(c=c.parentNode,!c)return[];return b[3]?a(b[3],q):[q]}if(b[3]&&p.getElementsByClassName)return p.getElementsByClassName(b[4]);if(b[5])if(q=
p.getElementsByTagName(b[5]),b[4]||b[6])l=(b[4]||"")+b[6];else return q}if(g)return 1===p.nodeType&&"object"!==p.nodeName.toLowerCase()?k(p,l,p.querySelectorAll):p.querySelectorAll(l);q||(q=p.getElementsByTagName("*"));for(var b=[],c=0,x=q.length;c<x;c++){var f=q[c];1==f.nodeType&&e(f,l,p)&&b.push(f)}return b},k=function(a,e,b){var c=a,q=a.getAttribute("id"),g=q||"__dojo__",d=a.parentNode,m=/^\s*[+~]/.test(e);if(m&&!d)return[];q?g=g.replace(/'/g,"\\$\x26"):a.setAttribute("id",g);m&&d&&(a=a.parentNode);
e=e.match(l);for(d=0;d<e.length;d++)e[d]="[id\x3d'"+g+"'] "+e[d];e=e.join(",");try{return b.call(a,e)}finally{q||c.removeAttribute("id")}};if(!b("dom-matches-selector"))var e=function(){function a(e,n,c){var b=n.charAt(0);if('"'==b||"'"==b)n=n.slice(1,-1);n=n.replace(/\\/g,"");var l=g[c||""];return function(a){return(a=a.getAttribute(e))&&l(a,n)}}function e(a){return function(e,b){for(;(e=e.parentNode)!=b;)if(a(e,b))return!0}}function b(a){return function(e,b){e=e.parentNode;return a?e!=b&&a(e,b):
e==b}}function c(a,e){return a?function(b,c){return e(b)&&a(b,c)}:e}var l="div"==f.tagName?"toLowerCase":"toUpperCase",d={"":function(a){a=a[l]();return function(e){return e.tagName==a}},".":function(a){var e=" "+a+" ";return function(b){return-1<b.className.indexOf(a)&&-1<(" "+b.className+" ").indexOf(e)}},"#":function(a){return function(e){return e.id==a}}},g={"^\x3d":function(a,e){return 0==a.indexOf(e)},"*\x3d":function(a,e){return-1<a.indexOf(e)},"$\x3d":function(a,e){return a.substring(a.length-
e.length,a.length)==e},"~\x3d":function(a,e){return-1<(" "+a+" ").indexOf(" "+e+" ")},"|\x3d":function(a,e){return 0==(a+"-").indexOf(e+"-")},"\x3d":function(a,e){return a==e},"":function(a,e){return!0}},m={};return function(l,g,q){var f=m[g];if(!f){if(g.replace(/(?:\s*([> ])\s*)|(#|\.)?((?:\\.|[\w-])+)|\[\s*([\w-]+)\s*(.?=)?\s*("(?:\\.|[^"])+"|'(?:\\.|[^'])+'|(?:\\.|[^\]])*)\s*\]/g,function(l,g,q,m,n,k,y){m?f=c(f,d[q||""](m.replace(/\\/g,""))):g?f=(" "==g?e:b)(f):n&&(f=c(f,a(n,y,k)));return""}))throw Error("Syntax error in query");
if(!f)return!0;m[g]=f}return f(l,q)}}();if(!b("dom-qsa"))var m=function(e,b){for(var c=e.match(l),g=[],d=0;d<c.length;d++){e=new String(c[d].replace(/\s*$/,""));e.indexOf=escape;for(var m=a(e,b),f=0,k=m.length;f<k;f++){var t=m[f];g[t.sourceIndex]=t}}c=[];for(d in g)c.push(g[d]);return c};a.match=c?function(a,e,b){return b&&9!=b.nodeType?k(b,e,function(e){return c.call(a,e)}):c.call(a,e)}:e;return a})},"xstyle/core/load-css":function(){define([],function(){function b(b){if(c.createStyleSheet){var a=
c.createStyleSheet();a.cssText=b;return a.owningElement}a=c.createElement("style");a.setAttribute("type","text/css");a.appendChild(c.createTextNode(b));g.insertBefore(a,g.firstChild);return a}function d(d,a,k){var e=f[d];if(e)return m=b(e),a(m);var m=c.createElement("link");m.type="text/css";m.rel="stylesheet";m.href=d;var r=!k||!1!==k.wait;k=(k=navigator.userAgent.match(/AppleWebKit\/(\d+\.?\d*)/))&&+k[1];if(null===m.onload&&!(536>k))m.onload=function(){m.onload=null;m.onerror=null;r&&a(m)},m.onerror=
function(){console.error("Error loading stylesheet "+d);r&&a(m)};else if(r)var p=setInterval(function(){m.style&&(clearInterval(p),a(m))},15);(g||c.getElementsByTagName("head")[0]).appendChild(m);r||a(m)}var f="undefined"==typeof _css_cache?{}:_css_cache,c=document,g=c.head;d.insertCss=b;return d})},"dijit/main":function(){define(["dojo/_base/kernel"],function(b){return b.dijit})},"dojox/main":function(){define(["dojo/_base/kernel"],function(b){return b.dojox})},"MW/utils/BrowserCheck":function(){define("dojo/_base/window dojo/window dojo/dom-construct dojo/has dojo/i18n!l10n/nls/unsupportedErrorPage ./detect/css ./detect/object".split(" "),
function(b,d,f,c,g){var l={isBrowserValid:function(){var a=!0;c("quirks")?a=!1:c("css-enabled")?c("css-border-radius")?c("css-text-overflow")?c("object-create")||(a=!1):a=!1:a=!1:a=!1;return a},displayErrorAsOverlay:function(){f.create("div",{style:{position:"absolute",left:"0%",top:"0%","background-color":"grey","-moz-opacity":"0.7",opacity:".70",filter:"alpha(opacity\x3d70)",width:"100%",height:"100%",zIndex:"90"},id:"fadeDiv"},b.body());f.create("div",{style:{position:"relative",margin:"auto",
"margin-top":"12.35%",width:"400px",height:"300px",padding:"10px",border:"2px solid black","background-color":"#ffffff","z-index":"100","font-family":"Sans-serif"},id:"unsupportedBrowser","class":"content_module"},b.body()).innerHTML=g.unsupportedError}};return{load:function(a,c,e){l.isBrowserValid()?e():a?b.global.location=a:l.displayErrorAsOverlay()}}})},"dojo/window":function(){define("./_base/lang ./sniff ./_base/window ./dom ./dom-geometry ./dom-style ./dom-construct".split(" "),function(b,d,
f,c,g,l,a){d.add("rtl-adjust-position-for-verticalScrollBar",function(e,b){var c=f.body(b),d=a.create("div",{style:{overflow:"scroll",overflowX:"visible",direction:"rtl",visibility:"hidden",position:"absolute",left:"0",top:"0",width:"64px",height:"64px"}},c,"last"),l=a.create("div",{style:{overflow:"hidden",direction:"ltr"}},d,"last"),k=0!=g.position(l).x;d.removeChild(l);c.removeChild(d);return k});d.add("position-fixed-support",function(e,b){var c=f.body(b),d=a.create("span",{style:{visibility:"hidden",
position:"fixed",left:"1px",top:"1px"}},c,"last"),l=a.create("span",{style:{position:"fixed",left:"0",top:"0"}},d,"last"),k=g.position(l).x!=g.position(d).x;d.removeChild(l);c.removeChild(d);return k});var k={getBox:function(a){a=a||f.doc;var b="BackCompat"==a.compatMode?f.body(a):a.documentElement,c=g.docScroll(a);if(d("touch")){var l=k.get(a);a=l.innerWidth||b.clientWidth;b=l.innerHeight||b.clientHeight}else a=b.clientWidth,b=b.clientHeight;return{l:c.x,t:c.y,w:a,h:b}},get:function(a){if(d("ie")&&
k!==document.parentWindow){a.parentWindow.execScript("document._parentWindow \x3d window;","Javascript");var b=a._parentWindow;a._parentWindow=null;return b}return a.parentWindow||a.defaultView},scrollIntoView:function(a,b){try{a=c.byId(a);var k=a.ownerDocument||f.doc,p=f.body(k),v=k.documentElement||p.parentNode,s=d("ie"),q=d("webkit");if(!(a==p||a==v))if(!d("mozilla")&&(!s&&!q&&!d("opera")&&!d("trident"))&&"scrollIntoView"in a)a.scrollIntoView(!1);else{var x="BackCompat"==k.compatMode,y=Math.min(p.clientWidth||
v.clientWidth,v.clientWidth||p.clientWidth),G=Math.min(p.clientHeight||v.clientHeight,v.clientHeight||p.clientHeight),k=q||x?p:v,t=b||g.position(a),n=a.parentNode,q=function(a){return 6>=s||7==s&&x?!1:d("position-fixed-support")&&"fixed"==l.get(a,"position").toLowerCase()},K=this,A=function(a,b,e){"BODY"==a.tagName||"HTML"==a.tagName?K.get(a.ownerDocument).scrollBy(b,e):(b&&(a.scrollLeft+=b),e&&(a.scrollTop+=e))};if(!q(a))for(;n;){n==p&&(n=k);var h=g.position(n),z=q(n),H="rtl"==l.getComputedStyle(n).direction.toLowerCase();
if(n==k){h.w=y;h.h=G;if(k==v&&(s||d("trident"))&&H)h.x+=k.offsetWidth-h.w;if(0>h.x||!s||9<=s||d("trident"))h.x=0;if(0>h.y||!s||9<=s||d("trident"))h.y=0}else{var B=g.getPadBorderExtents(n);h.w-=B.w;h.h-=B.h;h.x+=B.l;h.y+=B.t;var w=n.clientWidth,C=h.w-w;0<w&&0<C&&(H&&d("rtl-adjust-position-for-verticalScrollBar")&&(h.x+=C),h.w=w);w=n.clientHeight;C=h.h-w;0<w&&0<C&&(h.h=w)}z&&(0>h.y&&(h.h+=h.y,h.y=0),0>h.x&&(h.w+=h.x,h.x=0),h.y+h.h>G&&(h.h=G-h.y),h.x+h.w>y&&(h.w=y-h.x));var D=t.x-h.x,E=t.y-h.y,I=D+t.w-
h.w,J=E+t.h-h.h,u,F;if(0<I*D&&(n.scrollLeft||n==k||n.scrollWidth>n.offsetHeight)){u=Math[0>D?"max":"min"](D,I);if(H&&(8==s&&!x||9<=s||d("trident")))u=-u;F=n.scrollLeft;A(n,u,0);u=n.scrollLeft-F;t.x-=u}if(0<J*E&&(n.scrollTop||n==k||n.scrollHeight>n.offsetHeight))u=Math.ceil(Math[0>E?"max":"min"](E,J)),F=n.scrollTop,A(n,0,u),u=n.scrollTop-F,t.y-=u;n=n!=k&&!z&&n.parentNode}}}catch(L){console.error("scrollIntoView: "+L),a.scrollIntoView(!1)}}};b.setObject("dojo.window",k);return k})},"dojo/i18n":function(){define("./_base/kernel require ./has ./_base/array ./_base/config ./_base/lang ./_base/xhr ./json module".split(" "),
function(b,d,f,c,g,l,a,k,e){d=b.i18n={};var m=/(^.*(^|\/)nls)(\/|$)([^\/]*)\/?([^\/]*)/,r=function(a,b,e,c){var d=[e+c];b=b.split("-");for(var g="",l=0;l<b.length;l++)if(g+=(g?"-":"")+b[l],!a||a[g])d.push(e+g+"/"+c),d.specificity=g;return d},p={};a=b.getL10nName=function(a,c,d){var g=e.id+"!";d=d?d.toLowerCase():b.locale;a=a.replace(/\./g,"/");c=c.replace(/\./g,"/");d=/root/i.test(d)?a+"/nls/"+c:a+"/nls/"+d+"/"+c;return g+d};var v=function(a,b,e,c,d,g){a([b],function(f){var k=l.clone(f.root||f.ROOT),
h=r(!f._v1x&&f,d,e,c);a(h,function(){for(var a=1;a<h.length;a++)k=l.mixin(l.clone(k),arguments[a]);p[b+"/"+d]=k;k.$locale=h.specificity;g()})})},s=function(a){var b=g.extraLocale||[],b=l.isArray(b)?b:[b];b.push(a);return b};f("dojo-unit-tests")&&(d.unitTests=[]);return l.mixin(d,{dynamic:!0,normalize:function(a,b){return/^\./.test(a)?b(a):a},load:function(a,e,d){a=m.exec(a);var g=a[1]+"/",f=a[5]||a[4],k=g+f,r=(a=a[5]&&a[4])||b.locale||"",A=k+"/"+r;a=a?[r]:s(r);var h=a.length,z=function(){--h||d(l.delegate(p[A]))};
c.forEach(a,function(a){p[k+"/"+a]?z():v(e,k,g,f,a,z)})},cache:p,getL10nName:a})})},"l10n/nls/unsupportedErrorPage":function(){define({root:{unsupportedError:"\x3cp\x3eWe're sorry...\x3c/p\x3e\x3cp\x3eThe page you're accessing is not supported on this browser.\x3c/p\x3e\x3cp\x3ePlease change or upgrade to one of the following supported browsers:\x3c/p\x3e\x3cul\x3e\x3cli\x3eOn Windows Vista or Windows 7:\x3cul\x3e\x3cli\x3eChrome 12 and above\x3c/li\x3e\x3cli\x3eFirefox 7 and above\x3c/li\x3e\x3cli\x3eInternet Explorer 9 and above\x3c/li\x3e\x3c/ul\x3e\x3c/li\x3e\x3cli\x3eOn Mac 10.6 or Mac 10.7:\x3cul\x3e\x3cli\x3eSafari 5.0 and above\x3c/li\x3e\x3cli\x3eChrome 12 and above\x3c/li\x3e\x3c/ul\x3e\x3c/li\x3e\x3c/ul\x3e"}})},
"MW/utils/detect/css":function(){define(["dojo/has"],function(b){function d(b,d){var a=!1,c=b.charAt(0).toUpperCase()+b.slice(1),e=f.length,m=d.style;if("string"===typeof m[b])a=!0;else for(;e;)if(e-=1,"string"===typeof m[f[e]+c]){a=!0;break}return a}var f=["Webkit","Moz","O","ms","Khtml"],c=b.add;c("css-enabled",function(b,d,a){var c;b=d.documentElement;var e;if(!(e=d.body))c=!0,e=b.insertBefore(d.createElement("body"),b.firstChild);b=e;e=a.style.display;a.style.display="none";b.insertBefore(a,b.firstChild);
d=0===a.offsetWidth;b.removeChild(a);a.style.display=e;c&&b.parentNode.removeChild(b);return d});c("css-content-box",function(d,c,a){var f,e;d=c.documentElement;var m=null;if(b("css-enabled")){if(!(e=c.body))f=!0,e=d.insertBefore(c.createElement("body"),d.firstChild);a.style.cssText="position: absolute; top: -4000px; width: 40px; height: 40px; border: 1px solid black;";e.insertBefore(a,e.firstChild);m=40===a.clientWidth;e.removeChild(a);a.style.cssText=""}f&&e.parentNode.removeChild(e);return m});
c("css-position-fixed",function(d,c,a){var f,e,m=c.documentElement,r=null;if(b("css-enabled")){d=a.cloneNode(!1);if(!(e=c.body))f=!0,e=m.insertBefore(c.createElement("body"),m.firstChild);c=e.style.cssText;e.style.cssText="padding:0;margin:0";a.style.cssText="position:fixed;top:42px";e.insertBefore(d,e.firstChild);e.insertBefore(a,d);r=a.offsetTop!==d.offsetTop;e.removeChild(a);e.removeChild(d);e.style.cssText=c;a.style.cssText=""}f&&e.parentNode.removeChild(e);return r});c("css-rgba",function(d,
c,a){d=/^rgba/;c=null;if(b("css-enabled"))try{a.style.color="rgba(1,1,1,0.5)",c=d.test(a.style.color),a.style.color=""}catch(f){}return c});c("css-border-radius",function(b,c,a){return d("borderRadius",a)});c("css-box-shadow",function(b,c,a){return d("boxShadow",a)});c("css-box-sizing",function(b,c,a){return d("boxSizing",a)});c("css-opacity",function(b,c,a){return d("opacity",a)});c("css-opacity-filter",function(c,d){return!b("css-opacity")&&"undefined"!==typeof d.documentElement.filters});c("css-resize",
function(b,c,a){return d("resize",a)});c("css-selectable",function(b,c,a){return d("userSelect",a)});c("css-style-float",function(b,c,a){return d("styleFloat",a)});c("css-pointerevents",function(b,c,a){return d("pointerEvents",a)});c("css-text-overflow",function(b,c,a){return d("textOverflow",a)});c("css-text-shadow",function(b,c,a){return d("textShadow",a)});c("css-transform",function(b,c,a){return d("transform",a)});return b})},"MW/utils/detect/object":function(){define(["dojo/has"],function(b){var d=
b.add,f={}.toString,c=Object;d("object-create",function(){return"[object Function]"===f.call(c.create)});d("object-getprototypeof",function(){return"[object Function]"===f.call(c.getPrototypeOf)});d("object-seal",function(){return"[object Function]"===f.call(c.seal)});d("object-freeze",function(){return"[object Function]"===f.call(c.freeze)});d("object-issealed",function(){return"[object Function]"===f.call(c.isSealed)});d("object-isfrozen",function(){return"[object Function]"===f.call(c.isFrozen)});
d("object-keys",function(){return"[object Function]"===f.call(c.keys)});d("object-preventextensions",function(){return"[object Function]"===f.call(c.preventExtensions)});d("object-isextensible",function(){return"[object Function]"===f.call(c.isExtensible)});d("object-defineproperty",function(){return"[object Function]"===f.call(c.defineProperty)});d("object-defineproperties",function(){return"[object Function]"===f.call(c.defineProperties)});d("object-getownpropertydescriptor",function(){return"[object Function]"===
f.call(c.getOwnPropertyDescriptor)});d("object-getownpropertynames",function(){return"[object Function]"===f.call(c.getOwnPropertyNames)});d("object-es5",function(){return b("object-create")&&b("object-defineproperties")&&b("object-defineproperty")&&b("object-freeze")&&b("object-getownpropertydescriptor")&&b("object-getownpropertynames")&&b("object-getprototypeof")&&b("object-isextensible")&&b("object-isfrozen")&&b("object-issealed")&&b("object-keys")&&b("object-preventextensions")&&b("object-seal")});
return b})}}});define("InstallServiceHandler/browsercheck",[],1);
//# sourceMappingURL=browsercheck.js.map